### PR TITLE
Talk about impact on nomination process

### LINKED ISSUE #7: Should ICE agents wait for all prflx candidates before sending USE-CANDIDATE?
[from the list]
... I think this implies that one shouldn't be too hasty to declare ICE completion either.

Since some implementations may malfunction if they don't get a USE-CANDIDATE quickly, I am not sure if we can wait the full STUN timeout interval, but perhaps a somewhat shorter delay (e.g. a few seconds) could be recommended before sending USE-CANDIDATE.

### PR DESCRIPTION
**Pull request by juberti**
Fixes #7

### CODE REVIEW

**Review by cdh4u — COMMENTED** [review]
- Since the timer is discussed earlier in the section, I suggest s/this timer/the timer

- s/The specification/This specification

- I think it would good to explicitly indicate that nomination is allowed before the timer expires, while we later talk about why waiting is a good idea. So, something like:

"This specification does not define a minimum duration for ICE processing, and the controlling ICE agent is allowed to nominate candidate pairs before the timer elapses, , but in order to nominate the best…"

(Don't think we need to include "selected", because that is too low level detail)

- Suggested modified last sentence:

"Therefore, the controlling ICE agent SHOULD wait a sufficient amount of time before nominating
 candidate pairs, and it MAY use the timer described above to do so."

**Comment by juberti** [comment]
> * Since the timer is discussed earlier in the section, I suggest s/this timer/the timer

OK.

> * s/The specification/This specification

I was referring to 8445 here, so I changed the text to 'That specification'

> * I think it would good to explicitly indicate that nomination is allowed before the timer expires, while we later talk about why waiting is a good idea. So, something like:
> 
> "This specification does not define a minimum duration for ICE processing, and the controlling ICE agent is allowed to nominate candidate pairs before the timer elapses, , but in order to nominate the best…"

I'm not convinced this is needed; it seems we've made the point that the ICE agent should wait, but it doesn't have to.

> (Don't think we need to include "selected", because that is too low level detail)

Agreed, it was also incorrect, since pairs aren't selected until they are nominated

> * Suggested modified last sentence:
> 
> "Therefore, the controlling ICE agent SHOULD wait a sufficient amount of time before nominating
> candidate pairs, and it MAY use the timer described above to do so."

Looks good.

**Comment by juberti** [comment]
PTAL

**Review by pthatcherg — APPROVED** [review]

**Comment by cdh4u** [comment]
In general, the text looks good, but I still would like to explicitly say that nomination can take place before the timer elapses.

This is related to #15, which talks about minimum amount of time to run ICE. It really sounds like an agent MUST run ICE for a certain time, even if it is able to nominate before that.

What we need to point out is that a checklist is not set to Failed before the timer elapses, but that a pair within the checklist for sure can be nominated before the timer elapses.

**Comment by juberti** [comment]
PTAL at the latest.

**Comment by cdh4u** [comment]
Why do we need to talk about non-relay candidates etc? Why not simply say "if the agent believes it has received the best available candidates, including possible peer-reflexive candidates, and has created Valid pairs based on them, the agent SHOULD...".

**Comment by juberti** [comment]
it's just an example, as indicated by 'e.g.'. But I'll try another version with some of your suggested text.

**Comment by juberti** [comment]
OK, the previous text may have been over-specific. I think the new text is a reasonable compromise, PTAL.

**Review by cdh4u — APPROVED** [review]
Looks good.

**Review by akeranen — APPROVED** [review]

**Pull request merged**
